-- Development User Setup Guide
-- 
-- The profile will be automatically created by the handle_new_user() trigger
-- when you create the auth user in Supabase Dashboard

-- Steps to set up your development user:
-- 
-- 1. Go to your Supabase project → Authentication → Users
-- 2. Click "Add user"
-- 3. Use the email and password from your .env.local:
--    - NEXT_PUBLIC_DEV_EMAIL
--    - NEXT_PUBLIC_DEV_PASSWORD
-- 4. Copy the generated User UID
-- 5. Update NEXT_PUBLIC_DEFAULT_USER_ID in your .env.local with that UUID
--
-- The trigger will automatically create a profile with:
-- - username: based on email or 'user_' + auth user id
-- - first_name: from user metadata or extracted from email
-- - last_name: from user metadata if available
--
-- If you need to update the profile later, you can run:
-- 
-- UPDATE profiles SET
--     username = 'your-preferred-username',
--     first_name = 'Your First Name',
--     last_name = 'Your Last Name'
-- WHERE id = 'your-user-uuid-here';
